apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelTraining
metadata:
  annotation:
    name: wine-quality
    version: "1.0"
  name: wine-quality-training
spec:
  toolchain: legion-mlflow
  vcsName: legion
  workDir: examples/wine-quality
  entrypoint: main
  hyperparameters:
    alpha: 1.0